const testData = [
    {
        fullName: "Robert Fox",
        role: "Customer",
        avatar: "/images/avatar-1.jpg",
        testimonial: "Pellentesque eu nibh eget mauris congue mattis mattis nec tellus. Phasellus imperdiet elit eu magna dictum, bibendum cursus velit sodales. Donec sed neque eget",
        rate: 5,
    },
    {
        fullName: "Dianne Russell",
        role: "Customer",
        avatar: "/images/avatar-2.jpg",
        testimonial: "Pellentesque eu nibh eget mauris congue mattis mattis nec tellus. Phasellus imperdiet elit eu magna dictum, bibendum cursus velit sodales. Donec sed neque eget",
        rate: 5,
    },
    {
        fullName: "Eleanor Pena",
        role: "Customer",
        avatar: "/images/avatar-3.jpg",
        testimonial: "Pellentesque eu nibh eget mauris congue mattis mattis nec tellus. Phasellus imperdiet elit eu magna dictum, bibendum cursus velit sodales. Donec sed neque eget",
        rate: 5,
    },
    {
        fullName: "Robert Fox",
        role: "Customer",
        avatar: "/images/avatar-1.jpg",
        testimonial: "Pellentesque eu nibh eget mauris congue mattis mattis nec tellus. Phasellus imperdiet elit eu magna dictum, bibendum cursus velit sodales. Donec sed neque eget",
        rate: 5,
    },
    {
        fullName: "Dianne Russell",
        role: "Customer",
        avatar: "/images/avatar-2.jpg",
        testimonial: "Pellentesque eu nibh eget mauris congue mattis mattis nec tellus. Phasellus imperdiet elit eu magna dictum, bibendum cursus velit sodales. Donec sed neque eget",
        rate: 5,
    },
    {
        fullName: "Eleanor Pena",
        role: "Customer",
        avatar: "/images/avatar-3.jpg",
        testimonial: "Pellentesque eu nibh eget mauris congue mattis mattis nec tellus. Phasellus imperdiet elit eu magna dictum, bibendum cursus velit sodales. Donec sed neque eget",
        rate: 5,
    },
    {
        fullName: "Eleanor Pena",
        role: "Customer",
        avatar: "/images/avatar-3.jpg",
        testimonial: "Pellentesque eu nibh eget mauris congue mattis mattis nec tellus. Phasellus imperdiet elit eu magna dictum, bibendum cursus velit sodales. Donec sed neque eget",
        rate: 5,
    },
    {
        fullName: "Robert Fox",
        role: "Customer",
        avatar: "/images/avatar-1.jpg",
        testimonial: "Pellentesque eu nibh eget mauris congue mattis mattis nec tellus. Phasellus imperdiet elit eu magna dictum, bibendum cursus velit sodales. Donec sed neque eget",
        rate: 5,
    },
    {
        fullName: "Dianne Russell",
        role: "Customer",
        avatar: "/images/avatar-2.jpg",
        testimonial: "Pellentesque eu nibh eget mauris congue mattis mattis nec tellus. Phasellus imperdiet elit eu magna dictum, bibendum cursus velit sodales. Donec sed neque eget",
        rate: 5,
    },
    {
        fullName: "Eleanor Pena",
        role: "Customer",
        avatar: "/images/avatar-3.jpg",
        testimonial: "Pellentesque eu nibh eget mauris congue mattis mattis nec tellus. Phasellus imperdiet elit eu magna dictum, bibendum cursus velit sodales. Donec sed neque eget",
        rate: 5,
    },
    {
        fullName: "Robert Fox",
        role: "Customer",
        avatar: "/images/avatar-1.jpg",
        testimonial: "Pellentesque eu nibh eget mauris congue mattis mattis nec tellus. Phasellus imperdiet elit eu magna dictum, bibendum cursus velit sodales. Donec sed neque eget",
        rate: 5,
    },
    {
        fullName: "Dianne Russell",
        role: "Customer",
        avatar: "/images/avatar-2.jpg",
        testimonial: "Pellentesque eu nibh eget mauris congue mattis mattis nec tellus. Phasellus imperdiet elit eu magna dictum, bibendum cursus velit sodales. Donec sed neque eget",
        rate: 5,
    },
    {
        fullName: "Eleanor Pena",
        role: "Customer",
        avatar: "/images/avatar-3.jpg",
        testimonial: "Pellentesque eu nibh eget mauris congue mattis mattis nec tellus. Phasellus imperdiet elit eu magna dictum, bibendum cursus velit sodales. Donec sed neque eget",
        rate: 5,
    },
    {
        fullName: "Eleanor Pena",
        role: "Customer",
        avatar: "/images/avatar-3.jpg",
        testimonial: "Pellentesque eu nibh eget mauris congue mattis mattis nec tellus. Phasellus imperdiet elit eu magna dictum, bibendum cursus velit sodales. Donec sed neque eget",
        rate: 5,
    },
];

export default testData;